spring.application.name=sports_event_ticketing_platform
server.port=8081
spring.datasource.url = jdbc:postgresql://localhost:5432/postgres
spring.datasource.username = postgres
<<<<<<< HEAD
spring.datasource.password = 9eq5s@IXgh
=======
spring.datasource.password = 9eq5s@IXgh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=your-very-long-secret-key-for-jwt-generation-at-least-32-characters
jwt.expiration=3600000

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000

app.redis.otp-ttl=120
app.redis.search-cache-ttl=300
app.redis.profile-cache-ttl=600
app.redis.reservation-lock-ttl=600
>>>>>>> origin/backend
